spring.application.name=workflow-engine

spring.security.user.name=ps
spring.security.user.password=12345
# =====================================================
# LOAD .env FILE (SPRING BOOT NATIVE \u2013 IMPORTANT)
# =====================================================
spring.config.import=optional:file:.env[.properties]

# =====================================================
# SERVER
# =====================================================
server.port=8080

# =====================================================
# DATABASE (MYSQL)
# Values are loaded from .env
# =====================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# =====================================================
# SMTP MAIL
# Values are loaded from .env
# =====================================================
#spring.mail.host=${MAIL_HOST}
#spring.mail.port=${MAIL_PORT}
#
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.default-encoding=UTF-8

# =====================================================
# JWT SECRET
# Values are loaded from .env
# =====================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}